allow for modifying Alert copy-button behavior
alerta/alerta-webui pull request #555
Opened 2023-03-04 08:23 UTC by emillen

Use nunjucks-templates to modify AlertDetail copy-button behavior

**Description**
Sometimes you want the ability to copy an alert so you can paste into a third party system (slack, email, etc) in human-readable way. This PR allows for setting a nunjuck-template used for formatting the JSON before putting it in the clipboard.

Fixes  #522 

**Changes**
Include a brief summary of changes...
- Install [Nujucks](https://mozilla.github.io/nunjucks/) (jinja2-like templating engine)
- When `clipboard_template` setting is set, the webui uses its contents as template for the AlertDetail copy button
- If `clipboard_template` is not set, it defaults to previous behavior

If you think this is a good idea and merge this, I will add PR's for adding the setting in the backend, and also add it to the docs.

---
**Ex:**

Provided following alert-json
```json
{
  "text": "this is a major alert",
  "environment": "prod"
}
```
and this template
```jinja
[{{environment | upper}}] Alert! 
{{text}}
```
would put the following text in your clipboard
```
[PROD] Alert!
this is a major alert
```

2023-03-06 22:02 UTC, kennhardy approved these changes
Looks good. Approved together with https://github.com/alerta/alerta/pull/1814

2023-03-07 21:49 UTC, satterly requested changes

2023-03-07 21:49 UTC, satterly commented on src/components/AlertDetail.vue
> +    clipboardCopy(obj) {
Can you call the parameter `item` instead of `obj`?

2023-03-09 13:23 UTC, emillen commented
What do you say - does this need more work, or are we fine like this?

2023-03-09 13:47 UTC, satterly commented
Actually ignore that. There's probably nothing different. I'll merge.

2023-03-09 13:47 UTC, merged